## National Institute of Technology Karnatata, Surathkal
## Department of Electronics and Communication Engg.

## DL Lab : Assignment 4

Q.1(a).Write python from scratch for 2D Linear convolution between input=np.array([[1,2,3],[4,5,6],[7,8,9]])and filter= np.array([[1,2,1],[0,0,0],[-1,-2,-1]])
<o>
(b).Write python from scratch for 2d Linear convolution between input image(lena.jpg) and  kernel = np.array([[1, 2, 1],[2, 4, 2],[1, 2, 1]]))/16 
(c) Compute number of multiplications and parameters required for 2D Linear Convolution in part (a) and part(b)
(d) Apply Max pooling and Average pooling on convoved image in part (b)

In [4]:
%%time
import cv2
import numpy as np
ip = np.array([[1,2,3],[4,5,6],[7,8,9]])
ip_chg = np.pad(ip,(1,1),'constant', constant_values=0)
filt = np.array([[1,2,1],[0,0,0],[-1,-2,-1]])
op = np.zeros(np.shape(ip)[0]*np.shape(ip)[0])
p=0
for i in range(np.shape(ip)[0]):
    for j in range(np.shape(ip)[1]):
        mat = ip_chg[i:np.shape(filt)[0]+i,j:np.shape(filt)[1]+j]
        op[p]=np.sum(mat*filt)
        p=p+1
op = op.reshape(np.shape(ip)[0],np.shape(ip)[0])    

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 460 µs


In [1]:
import cv2
import numpy as np
input=np.array([[1,2,3],[4,5,6],[7,8,9]])
filter= np.array([[1,2,1],[0,0,0],[-1,-2,-1]])
o=np.zeros((3,3))
input=np.pad(input,(1,1),mode="constant",constant_values=0)
for i in range(3):
    for j in range(3):
        for k in range(3):
            for l in range(3):
                o[i][j]+=input[i+k][j+l]*filter[k][l]
print(o)


[[-13. -20. -17.]
 [-18. -24. -18.]
 [ 13.  20.  17.]]


In [49]:
def lin_conv_2D(ip,filt,mult):
    ip_chg = np.pad(ip,(1,1),'constant', constant_values=0)
    op = np.zeros(np.shape(ip)[0]*np.shape(ip)[0])
    p=0
    for i in range(np.shape(ip)[0]):
        for j in range(np.shape(ip)[1]):
            mat = ip_chg[i:np.shape(filt)[0]+i,j:np.shape(filt)[1]+j]
            op[p]=int(np.round(np.sum(mat*filt)))
            mult = mult + mat.shape[0]*filt.shape[0]
            p=p+1
    op = op.reshape(np.shape(ip)[0],np.shape(ip)[0])
    return op,mult

In [50]:
import cv2
import numpy as np
img = cv2.imread('lena.jpg')
img_r = img[:,:,0]
img_b = img[:,:,1]
img_g = img[:,:,2]

mult = 0

kernel = np.array([[1, 2, 1],[2, 4, 2],[1, 2, 1]])/16
img_lin2d_r,mult1 = lin_conv_2D(img_r, kernel, mult)
img_lin2d_g,mult2 = lin_conv_2D(img_g, kernel, mult)
img_lin2d_b,mult3 = lin_conv_2D(img_b, kernel, mult)

In [52]:
img_conv = np.zeros((np.shape(img)[0]*np.shape(img)[1]*np.shape(img)[2]))
img_conv = np.reshape(img_conv,(np.shape(img)[0],np.shape(img)[1],np.shape(img)[2]))
img_conv[:,:,0]=img_lin2d_r
img_conv[:,:,1]=img_lin2d_g
img_conv[:,:,2]=img_lin2d_b

print("Total no. of Multiplications=",(mult1+mult2+mult3))

Total no. of Multiplications= 7077888


In [11]:
cv2.imshow('Orignal_Image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.imshow('Convolved_Image',img_conv)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
img_conv

array([[[ 66., 128.,  75.],
        [ 88., 170., 100.],
        [ 88., 170., 100.],
        ...,
        [ 94., 172., 106.],
        [ 81., 158.,  93.],
        [ 54., 112.,  64.]],

       [[ 88., 170., 100.],
        [117., 227., 134.],
        [117., 227., 134.],
        ...,
        [130., 232., 145.],
        [113., 214., 128.],
        [ 77., 152.,  88.]],

       [[ 88., 170., 100.],
        [117., 227., 134.],
        [117., 227., 134.],
        ...,
        [134., 233., 147.],
        [118., 216., 131.],
        [ 81., 154.,  91.]],

       ...,

       [[ 44.,  68.,  23.],
        [ 59.,  91.,  31.],
        [ 59.,  91.,  31.],
        ...,
        [ 71., 160.,  79.],
        [ 72., 164.,  82.],
        [ 54., 125.,  63.]],

       [[ 44.,  68.,  23.],
        [ 59.,  91.,  31.],
        [ 59.,  91.,  31.],
        ...,
        [ 72., 163.,  82.],
        [ 73., 168.,  86.],
        [ 56., 127.,  66.]],

       [[ 33.,  51.,  17.],
        [ 44.,  68.,  23.],
        [ 44.,  

In [18]:
def max_pool(ip):
    filt = np.array([[1, 1, 1],[1, 1, 1],[1, 1, 1]])
    rows = np.shape(ip)[0]-np.shape(filt)[0]+1
    columns = np.shape(ip)[1]-np.shape(filt)[0]+1
    op = np.zeros(rows*columns)
    p=0
    for i in range(rows):
        for j in range(columns):
            mat = ip[i:np.shape(filt)[0]+i,j:np.shape(filt)[0]+j]
            op[p]=np.round(np.max(mat*filt))
            p=p+1
    op = np.reshape(op,(rows,columns))   
    return op

img_conv_r = max_pool(img_conv)
img_conv_g = max_pool(img_conv)
img_conv_b = max_pool(img_conv)
img_max = np.zeros((np.shape(img_conv_r)[0]*np.shape(img_conv_r)[1]*np.shape(img)[2]))
img_max = np.reshape(img_max,(np.shape(img_conv_r)[0],np.shape(img_conv_r)[1],np.shape(img)[2]))
img_max[:,:,0]=img_conv_r
img_max[:,:,1]=img_conv_g
img_max[:,:,2]=img_conv_b

In [20]:
def avg_pool(ip):
    filt = np.array([[1, 1, 1],[1, 1, 1],[1, 1, 1]])
    rows = np.shape(ip)[0]-np.shape(filt)[0]+1
    columns = np.shape(ip)[1]-np.shape(filt)[0]+1
    op = np.zeros(rows*columns)
    p=0
    for i in range(rows):
        for j in range(columns):
            mat = ip[i:np.shape(filt)[0]+i,j:np.shape(filt)[0]+j]
            op[p]=np.round(np.max(mat*filt))
            p=p+1
    op = np.reshape(op,(rows,columns))   
    return op

img_conv_ravg = avg_pool(img_conv)
img_conv_gavg = avg_pool(img_conv)
img_conv_bavg = avg_pool(img_conv)
img_avg = np.zeros((np.shape(img_conv_ravg)[0]*np.shape(img_conv_ravg)[1]*np.shape(img)[2]))
img_avg = np.reshape(img_max,(np.shape(img_conv_ravg)[0],np.shape(img_conv_ravg)[1],np.shape(img)[2]))
img_avg[:,:,0]=img_conv_ravg
img_avg[:,:,1]=img_conv_gavg
img_avg[:,:,2]=img_conv_bavg

In [21]:
img_avg

array([[[227., 227., 227.],
        [227., 227., 227.],
        [227., 227., 227.],
        ...,
        [248., 248., 248.],
        [245., 245., 245.],
        [233., 233., 233.]],

       [[227., 227., 227.],
        [227., 227., 227.],
        [227., 227., 227.],
        ...,
        [248., 248., 248.],
        [245., 245., 245.],
        [233., 233., 233.]],

       [[227., 227., 227.],
        [227., 227., 227.],
        [227., 227., 227.],
        ...,
        [248., 248., 248.],
        [245., 245., 245.],
        [233., 233., 233.]],

       ...,

       [[ 91.,  91.,  91.],
        [ 91.,  91.,  91.],
        [ 91.,  91.,  91.],
        ...,
        [160., 160., 160.],
        [164., 164., 164.],
        [164., 164., 164.]],

       [[ 91.,  91.,  91.],
        [ 91.,  91.,  91.],
        [ 91.,  91.,  91.],
        ...,
        [163., 163., 163.],
        [168., 168., 168.],
        [168., 168., 168.]],

       [[ 91.,  91.,  91.],
        [ 91.,  91.,  91.],
        [ 91.,  

Q.2.(a)Write python from scratch for 2D Spatial Separbale convolution between input image(lena.jpg) and   Gausian filter 
 = np.array([1,4,6,4,1],[4,16,24,16,4],[6,24,36,24,6],[4,16,24,16,4],[1,4,6,4,1])/256
 (b) Compute number of multiplications and parameters required for2D Spatial Separbale convolution

In [32]:
def spatial_2d_separable(ip,filt,mult):
    filt = np.array([[1, 1, 1],[1, 1, 1],[1, 1, 1]])
    rows = np.shape(ip)[0]-np.shape(filt)[0]+1
    columns = np.shape(ip)[1]-np.shape(filt)[0]+1
    op = np.zeros(rows*columns)
    p=0
    for i in range(rows):
        for j in range(columns):
            mat = ip[i:np.shape(filt)[0]+i,j:np.shape(filt)[0]+j]
            op[p]=np.round(np.max(mat*filt))
            mult = mult + mat.shape[0]*filt.shape[0]
            p=p+1
    op = np.reshape(op,(rows,columns))   
    return op,mult

In [41]:
import cv2
import numpy as np

filt = np.array([[1,4,6,4,1],[4,16,24,16,4],[6,24,36,24,6],[4,16,24,16,4],[1,4,6,4,1]])
min_arr = np.zeros(np.shape(filt)[0])
for i in range(np.shape(filt)[0]):
    min_arr[i] = np.abs(np.min(filt[:,i]))
max_a = np.max(min_arr)
pos_maxa = np.argmax(min_arr)
A = filt[:,pos_maxa]
post = A/max_a
pre = min_arr
post = post.reshape(post.shape[0],1)
pre = pre.reshape(1,pre.shape[0])

img = cv2.imread('lena.jpg')

img_r = img[:,:,0]
img_b = img[:,:,1]
img_g = img[:,:,2]

rimg_conv2_sep = spatial_2d_separable(img_r,pre)
rimg_conv2_sep = spatial_2d_separable(rimg_conv2_sep,post)
rimg_conv2_sep = rimg_conv2_sep

gimg_conv2_sep = spatial_2d_separable(img_g,pre)
gimg_conv2_sep = spatial_2d_separable(gimg_conv2_sep,post)
gimg_conv2_sep = gimg_conv2_sep

bimg_conv2_sep = spatial_2d_separable(img_b,pre)
bimg_conv2_sep = spatial_2d_separable(bimg_conv2_sep,post)
bimg_conv2_sep = bimg_conv2_sep

img_2d_sep = np.zeros((np.shape(rimg_conv2_sep)[0]*np.shape(rimg_conv2_sep)[1]*np.shape(img)[2]))
img_2d_sep = np.reshape(img_2d_sep,(np.shape(rimg_conv2_sep)[0],np.shape(rimg_conv2_sep)[1],np.shape(img)[2]))
img_2d_sep[:,:,0]=rimg_conv2_sep
img_2d_sep[:,:,1]=gimg_conv2_sep
img_2d_sep[:,:,2]=bimg_conv2_sep

In [42]:
img_2d_sep

array([[[117., 227., 134.],
        [117., 227., 134.],
        [117., 227., 134.],
        ...,
        [152., 253., 163.],
        [152., 253., 163.],
        [152., 253., 163.]],

       [[117., 227., 134.],
        [117., 227., 134.],
        [117., 227., 134.],
        ...,
        [152., 253., 163.],
        [152., 253., 163.],
        [152., 253., 163.]],

       [[117., 227., 134.],
        [117., 227., 134.],
        [117., 227., 134.],
        ...,
        [152., 253., 163.],
        [152., 253., 163.],
        [152., 253., 163.]],

       ...,

       [[ 59.,  91.,  31.],
        [ 59.,  91.,  31.],
        [ 59.,  91.,  31.],
        ...,
        [ 71., 160.,  80.],
        [ 72., 165.,  83.],
        [ 73., 167.,  85.]],

       [[ 59.,  91.,  31.],
        [ 59.,  91.,  31.],
        [ 59.,  91.,  31.],
        ...,
        [ 72., 163.,  83.],
        [ 73., 169.,  87.],
        [ 75., 171.,  89.]],

       [[ 59.,  91.,  31.],
        [ 59.,  91.,  31.],
        [ 59.,  

Q.3.(a)Write python from scratch for 2D Depthwise Separbale convolution between input image(lena.jpg) and depthwise and pointwise  filters are as follows:
<o>
depthwise filter array = np.array([[[1, 2, 1], [2, 4, 2], [1, 2, 1]], 
                     [[1, 2, 1], [2, 4, 2], [1, 2, 1]], 
                     [[1, 2, 1], [2, 4, 2], [1, 2, 1]]])/16
   <o>                  
pointwise filter array= np.array([[1], [1], [1]])/512
<o>
(b)Compute number of multiplications and parameters required for 2D Depthwise Separbale convolutions

In [235]:
#Depthwise Separable Convolution
def conv_2d_depth(filt,ip):
    rows = np.shape(ip)[0]-np.shape(filt)[0]+1
    columns = np.shape(ip)[1]-np.shape(filt)[1]+1
    op = np.zeros(rows*columns)
    p=0
    for i in range(rows):
        for j in range(columns):
            mat = ip[i:np.shape(filt)[0]+i,j:np.shape(filt)[1]+j]
            op[p]=int(np.round(np.sum(mat*filt)))
            p=p+1
            mult=mult + mat.shape[0]*filt.shape[0]
    op = np.reshape(op,(rows,columns))   
    return op   

In [243]:
import cv2
import numpy as np
filter_array = np.array([[[1, 2, 1], [2, 4, 2], [1, 2, 1]], [[1, 2, 1], [2, 4, 2], [1, 2, 1]], [[1, 2, 1], [2, 4, 2], [1, 2, 1]]])/16
img = cv2.imread('lena.jpg')
img_r = img[:,:,0]
img_b = img[:,:,1]
img_g = img[:,:,2]
filt1 = filter_array[0,:,:]
filt2 = filter_array[1,:,:]
filt3 = filter_array[2,:,:]

img_r_conv = conv_2d_depth(filt1,img_r)
img_g_conv = conv_2d_depth(filt3,img_g)
img_b_conv = conv_2d_depth(filt3,img_b)

img_conv = np.zeros((np.shape(img_r_conv)[0]*np.shape(img_r_conv)[1]*np.shape(img)[2]))
img_conv = np.reshape(img_conv,(np.shape(img_r_conv)[0],np.shape(img_r_conv)[1],np.shape(img)[2]))
img_conv[:,:,0]=img_r_conv
img_conv[:,:,1]=img_r_conv
img_conv[:,:,2]=img_r_conv

In [265]:
#Pointwise Separable Convolution
def conv_2d_depth(filt,ip):
    rows = np.shape(ip)[0]-np.shape(filt)[0]+1
    columns = np.shape(ip)[1]-np.shape(filt)[0]+1
    op = np.zeros(rows*columns)
    p=0
    for i in range(rows):
        for j in range(columns):
            mat = ip[i:np.shape(filt)[0]+i,j:np.shape(filt)[0]+j]
            op[p]=np.round(np.sum(mat*filt))
            p=p+1
    op = np.reshape(op,(rows,columns))   
    return op


import cv2
import numpy as np
filter_array= np.array([[1], [1], [1]])/8
img_r = img[:,:,0]
img_b = img[:,:,1]
img_g = img[:,:,2]
filt1 = filter_array[0]
filt2 = filter_array[1]
filt3 = filter_array[2]

img_r_conv = conv_2d_depth(filt1,img_r)
img_g_conv = conv_2d_depth(filt2,img_g)
img_b_conv = conv_2d_depth(filt3,img_b)

img_conv = img_r_conv + img_g_conv + img_b_conv

In [266]:
img_conv

array([[60., 60., 60., ..., 63., 54., 48.],
       [60., 60., 60., ..., 63., 57., 51.],
       [60., 60., 60., ..., 66., 58., 53.],
       ...,
       [22., 22., 22., ..., 39., 40., 41.],
       [22., 22., 22., ..., 39., 41., 41.],
       [22., 22., 22., ..., 41., 41., 43.]])

Q.4.Write python from scratch for 2D Atrous/Dilated cnvolution between input image(lena.jpg) and filter which is given below with rate 3:
<o>
filter= np.array([[1, 2, 1],[2, 4, 2], [1, 2, 1]])/16
<o>                  

In [180]:
import cv2
import numpy as np

In [181]:
def filt_arr(dilation_rate, filt):
    rows = (np.shape(filt)[0])*dilation_rate-(dilation_rate-1)
    columns = (np.shape(filt)[1])*dilation_rate-(dilation_rate-1)
    filt_mod=np.zeros((rows,columns))
    filt = np.reshape(filt,(np.shape(filt)[0]*np.shape(filt)[0]))
    p=0
    for i in range(np.shape(filt_mod)[0]):
        if(i%dilation_rate==0):
            for j in range(np.shape(filt_mod)[1]):
                if((i+j)%dilation_rate==0):
                    filt_mod[i][j]=filt[p]
                    p=p+1
    return filt_mod                

In [182]:
def atrous_2d_conv(ip,filt_in,dilation_rate):
    filt = filt_arr(dilation_rate, filt_in)
    rows = np.shape(ip)[0]-np.shape(filt)[0]+1
    columns = np.shape(ip)[1]-np.shape(filt)[1]+1
    op = np.zeros(rows*columns)
    p=0
    for i in range(rows):
        for j in range(columns):
            mat = ip[i:np.shape(filt)[0]+i,j:np.shape(filt)[1]+j]
            op[p]=int(np.round(np.sum(mat*filt)))
            p=p+1
    op = np.reshape(op,(rows,columns))   
    return op

In [183]:
img = cv2.imread('lena.jpg')
dilation_rate = 3
img_r = img[:,:,0]
img_b = img[:,:,1]
img_g = img[:,:,2]

kernel = np.array([[1, 2, 1],[2, 4, 2],[1, 2, 1]])/16
img_atrous2d_r = atrous_2d_conv(img_r,filt,dilation_rate)
img_atrous2d_g = atrous_2d_conv(img_g,filt,dilation_rate)
img_atrous2d_b = atrous_2d_conv(img_b,filt,dilation_rate)

In [184]:
img_conv = np.zeros((np.shape(img_atrous2d_r)[0]*np.shape(img_atrous2d_r)[1]*np.shape(img)[2]))
img_conv = np.reshape(img_conv,(np.shape(img_atrous2d_r)[0],np.shape(img_atrous2d_r)[1],np.shape(img)[2]))
img_conv[:,:,0]=img_atrous2d_r
img_conv[:,:,1]=img_atrous2d_g
img_conv[:,:,2]=img_atrous2d_b

In [185]:
img_conv.shape

(506, 506, 3)